name: Build CV PDF

on:
  workflow_dispatch:
  push:
    paths:
      - "cv.tex"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Tex Live
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-xetex biber

      - name: Compile CV
        run: |
          pdflatex cv.tex
          biber cv || true
          pdflatex cv.tex

      - name: Commit PDF to build branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout -B build
          git add cv.pdf
          git commit -m "Update compiled PDF"
          git push -f origin build
