name: Build CV PDF

on:
  workflow_dispatch: # Allows manual run
  push:
    paths:
      - "cv.tex" # Runs automatically if cv.tex changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Compile CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv.tex

      - name: Commit PDF to repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add cv.pdf
          git commit -m "Update compiled CV PDF [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
